steps:
  # Step 1: Build Docker container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-python-app:$COMMIT_SHA', '.']

  # Step 2: Push Docker container to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/simple-python-app:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy simple-python-app \
          --image gcr.io/$PROJECT_ID/simple-python-app:$COMMIT_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
