steps:
  # Step 1: Copy files to the Cloud Storage bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp * gs://my-github-pipeline-bucket/

  # Step 2: Build and tag Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world:$COMMIT_SHA', '.']

  # Step 3: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world:$COMMIT_SHA']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'hello-world'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hello-world:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/hello-world:$COMMIT_SHA'

options:
  logging: 'CLOUD_LOGGING_ONLY'

service_account: '574565058652-compute@developer.gserviceaccount.com'
